steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$newcase-472813/newcase-backend', './backend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$newcase-472813/newcase-frontend', './frontend']
images:
  - 'gcr.io/$newcase-472813/newcase-backend'
  - 'gcr.io/$newcase-472813/newcase-frontend'
